---
title: Sabnanifootball
timezone: Asia/Jakarta
collections:
  big-banner:
    title: Big Banner
    output: true
  jumbotron:
    title: Jumbotron
    output: true
  micro-banner:
    title: Mini Banner
    output: true
  nav:
    title: Nav
    output: true
  posts:
    title: Posts
    output: true
  product:
    title: Product
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: nav
  values:
    layout: products
    permalink: "/product/"
- scope:
    path: ''
    type: product
  values:
    layout: product
    image:
    - "/uploads/image-tampak-depan.jpg"
    - "/uploads/image-tampak-belakang.jpg"
    brand: SABNANI
    price: 100000
    saleprice: 0
    color:
    - AS IMAGE
    size:
    - FREE SIZE
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
  values:
    layout: default
name: SABNANI FOOTBALL
description: Stadium, Apparel, Teamwear & Equipment Football
logo: http://raw.githubusercontent.com/kemtol/sabnanifootball/master/images/logo.png
igid: 225743173
igtoken: 225743173.1677ed0.a283cb278b0446caabe7000d363967a5
wa: 628567685884
google_analytics: 
url: http://sabnani.co.id
baseurl: 
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
