---
title: Sabnanifootball
timezone: Asia/Jakarta
collections:
  nav:
    title: Nav
    output: true
  posts:
    title: Posts
    output: true
  product:
    title: Product
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: nav
  values:
    layout: products
    permalink: "/product/"
- scope:
    path: ''
    type: product
  values:
    layout: product
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
  values:
    layout: default
name: SABNANI FOOTBALL
description: Sewa Lapangan Mini Soccer BSD, Tangerang, Jakarta.
logo: http://raw.githubusercontent.com/kemtol/sabnanifootball/master/images/logo.png
footer-links:
  email: 
  facebook: 
  instagram: 
  youtube: 
disqus: 
google_analytics: 
url: http://sabnani.co.id
baseurl: 
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
